---

- name: Create Syslog profile
  panos_syslog_profile:
    provider: '{{ provider }}'
    name: splunk

- name: Create Syslog Server profile
  panos_syslog_server:
    provider: '{{ provider }}'
    syslog_profile: splunk
    name: splunk_srv
    server: '{{ hostvars.SPLUNK.vm.nics | getUserLayerIP }}'
    syslog_port: 514
    transport: 'UDP'

- name: Create log forwarding profile
  panos_log_forwarding_profile:
    provider: '{{ provider }}'
    name: default

- name: Create log forwarding profiles
  panos_log_forwarding_profile_match_list:
    provider: '{{ provider }}'
    log_forwarding_profile: 'default'
    name: 'panos_{{ item }}'
    log_type: '{{ item }}'
    filter: "All Logs"
    syslog_profiles: ['splunk']
  loop:
    - traffic
    - threat
    - url
    - data
    - tunnel
    - auth

- name: Configure route for Syslog service
  panos_type_cmd:
    provider: '{{ provider }}'
    cmd: 'edit'
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']
      /deviceconfig/system/route
    element: |
      <route>
        <service>
          <entry name="syslog">
            <source>
              <address>100.10.30.1/24</address>
              <interface>ethernet1/4</interface>
            </source>
          </entry>
        </service>
      </route>

- name: Commit configuration
  panos_commit_firewall:
    provider: '{{ provider }}'
