---
# tasks file for modoboa-config

#- name: Parse scenario file
#  include_tasks: parse-scenario-file.yml

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Change Timezone
  community.general.timezone:
    name: 'Canada/Eastern'

- name: Prepare ansible controller
  include_tasks: prepare-ansible-controller.yml

- name: Set emailConfig
  set_fact:
    emailConfig: "{{ domainsAndAccounts | getEmailDomainsAndAccounts }}"

- name: Wait for the Server/API to come online
  uri:
    url: '{{ mail_srv_url }}'
    validate_certs: no
  register: _result
  until: _result.status == 200
  retries: 7200 # 720 * 5 seconds = 1hour * 10 = 10hours (60*60/5)
  delay: 5 # every 5sec

- name: Clean Modoboa configuration
  include_tasks: clean.yml
  when: configAction == 'clean' or configAction == 'configure'

- name: add domains and accounts
  include_tasks: add-domains-and-accounts.yml
  when: configAction == 'add' or configAction == 'configure'

- name: Cleanup
  include_tasks: clean-ansible-controller.yml
