---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5
- name: Gather facts
  setup:
- name: DNS configuration
  include_role:
    name: robertdebock.dns
