---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Create directory Templates
  file:
    path: /home/student/Templates
    state: directory
    owner: student
    group: student
    mode: '0755'

- name: copy exploit files
  copy:
    src: "exploit/{{ item }}"
    dest: "/home/student/Templates/{{ item }}"
    owner: "student"
    group: "student"
  loop:
    - emailConfig.ini
    - modo0001L.py
    - modo0001P.py

- name: copy bash scripts
  copy:
    src: "exploit/{{ item }}"
    dest: "/home/student/Templates/{{ item }}"
    owner: "student"
    group: "student"
    mode: "0755"
  loop:
    - runL.sh
    - runP.sh

- name: Create dir "/home/student/Desktop" if not already there
  file:
    path: "/home/student/Desktop/"
    state: directory
    owner: student
    group: student

- name: Create dir "/home/student/Desktop
  file:
    path: "/home/student/Desktop/"
    state: directory
    owner: student
    group: student

- name: copy Webmail shortcut
  copy:
    src: "uservm/Webmail.desktop"
    dest: "/home/student/Desktop/Webmail.desktop"
    owner: "student"
    group: "student"
    mode: "0777"

- name: Create dir "/home/student/Desktop/passwords
  file:
    path: "/home/student/Desktop/passwords/"
    state: directory
    owner: student
    group: student

- name: Create dir "/home/student/Desktop/resolution
  file:
    path: "/home/student/Desktop/resolution/"
    state: directory
    owner: student
    group: student

- name: copy password desktop files
  copy:
    src: passwords/{{ item }}
    dest: /home/student/Desktop/passwords/{{ item }}
    owner: student
    group: student
  loop:
    - usernames.txt
    - passwords.txt

- name: copy desktop files
  copy:
    src: resolutions/{{ item }}
    dest: /home/student/Desktop/resolution/{{ item }}
    owner: student
    group: student
    mode: '0777'
  loop:
    - resolution1280x768.sh
    - resolution1920x1080.sh

- name: Unarchive and place rockyou.txt to student Desktop
  shell: gzip -dk < /usr/share/wordlists/rockyou.txt.gz > /home/student/Desktop/passwords/rockyou.txt
