---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Create directory Templates
  file:
    path: /home/{{ user }}/Templates
    state: directory
    owner: {{ user }}
    group: {{ user }}
    mode: '0755'

- name: copy exploit files
  copy:
    src: "exploit/{{ item }}"
    dest: "/home/{{ user }}/Templates/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - emailConfig.ini
    - modo0001L.py
    - modo0001P.py

- name: copy bash scripts
  copy:
    src: "exploit/{{ item }}"
    dest: "/home/{{ user }}/Templates/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  loop:
    - runL.sh
    - runP.sh

- name: Create dir "/home/user/Desktop" if not already there
  file:
    path: "/home/{{ user }}/Desktop/"
    state: directory
    owner: {{ user }}
    group: {{ user }}

- name: Create dir /home/user/Desktop
  file:
    path: "/home/{{ user }}/Desktop/"
    state: directory
    owner: {{ user }}
    group: {{ user }}

- name: copy Webmail shortcut
  copy:
    src: "uservm/Webmail.desktop"
    dest: "/home/{{ user }}/Desktop/Webmail.desktop"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0777"

- name: Create dir /home/user/Desktop/passwords
  file:
    path: "/home/{{ user }}/Desktop/passwords/"
    state: directory
    owner: {{ user }}
    group: {{ user }}

- name: Create dir /home/user/Desktop/resolution
  file:
    path: "/home/{{ user }}/Desktop/resolution/"
    state: directory
    owner: {{ user }}
    group: {{ user }}

- name: copy password desktop files
  copy:
    src: passwords/{{ item }}
    dest: /home/{{ user }}/Desktop/passwords/{{ item }}
    owner: {{ user }}
    group: {{ user }}
  loop:
    - usernames.txt
    - passwords.txt

- name: copy desktop files
  copy:
    src: resolutions/{{ item }}
    dest: /home/{{ user }}/Desktop/resolution/{{ item }}
    owner: {{ user }}
    group: {{ user }}
    mode: '0777'
  loop:
    - resolution1280x768.sh
    - resolution1920x1080.sh

- name: Need to copy wpscan database
  copy:
    src: '.wpscan'
    dest: '/home/{{ user }}/'

- name: Unarchive and place rockyou.txt to user Desktop
  shell: gzip -dk < /usr/share/wordlists/rockyou.txt.gz > /home/{{ user }}/Desktop/passwords/rockyou.txt
