---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5
- name: Gather facts
  setup:
- name: Create dir "/etc/ssl/certs/" if needed
  file:
    path: "/etc/ssl/certs/"
    state: directory
- name: Create dir "/etc/ssl/certs/private" if needed
  file:
    path: "/etc/ssl/certs/private"
    state: directory
- name: copy ssl certificates
  copy:
    src: "{{ item.certificate_file }}" #"files/certs/kernelcars.com/SCADA_KERNELCARS_COM.crt"
    dest: "{{ item.certificate_file_dst }}"  #"/etc/ssl/certs/SCADA_KERNELCARS_COM.crt"
    owner: "root"
    group: "root"
  loop: "{{ sites_ssl }}"
- name: copy private keys
  copy:
    src: "{{ item.private_Key }}" # "files/certs/kernelcars.com/SCADA_KERNELCARS_COM.crt"
    dest: "{{ item.private_Key_dst }}" # "/etc/ssl/certs/SCADA_KERNELCARS_COM.crt"
    owner: "root"
    group: "root"
  loop: "{{ sites_ssl }}"
- name: Web configuration
  include_role:
    name: apache2-proxy-to-http
