---
- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Gather facts
  setup:

- name: copy ssl certificate
  copy:
    src: "files/certs/{{ item }}"
    dest: "/usr/local/share/ca-certificates/{{ item }}"
    owner: "root"
    group: "root"
  loop:
    - CITEF_ROOT_CA.crt
    - CITEF_INTERIM_CA.crt

- name: copy ssl certificate2
  copy:
    src: "files/certs/{{ item }}"
    dest: "/usr/share/ca-certificates/{{ item }}"
    owner: "root"
    group: "root"
  loop:
    - CITEF_ROOT_CA.crt
    - CITEF_INTERIM_CA.crt

- name: Import certificate for Firefox
  script: files/certs/linux-cert-install-firefox.sh /usr/share/ca-certificates/{{ item }}.crt CITEF_ROOT_CA
  loop:
    - CITEF_ROOT_CA
    - CITEF_INTERIM_CA

- name: update CAs
  shell: update-ca-certificates

- name: Restart Gophish
  service:
    name: gophish
    state: restarted
  when: ansible_hostname == 'GOPHISH'
