---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5
- name: Gather facts
  setup:

- name: Config syslog forwarding to SO for Enterprise LAN
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    line: "*.* @100.10.10.7"
  when: inventory_hostname == 'UBUNTU_WKS'

- name: Config syslog forwarding to SO for SCADA LAN
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    line: "*.* @100.10.10.2"
  when: inventory_hostname == 'SCADA_WKS'

- name: Config syslog forwarding to SO for WAN
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    line: "*.* @100.10.20.2"
  when: inventory_hostname == 'DMZ_SRV'

- name: Restart rsyslog daemon
  service:
    name: rsyslog
    state: restarted
