---
galaxy_info:
  author: Robert de Bock
  role_name: dns
  description: Install and configure dns on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Amazon
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - bind
    - dns
    - networking
    - system
    - resolving
    - named
    - centos

dependencies: []
