---

- name: Config VyOS
  VyOSConfig:
    default_gw: 100.100.0.1
    interfaces:
      - id: 100
        adapter: eth0
        ip: 100.10.10.6
        mask: 24
        zone: LAN
      - id: 101
        adapter: eth1
        ip: 100.10.20.1
        mask: 24
        zone: DMZ
      - id: 102
        adapter: eth2
        ip: 100.100.0.2
        mask: 24
        zone: WAN
      - id: 102
        adapter: eth3
        ip: 100.10.30.1
        mask: 24
        zone: SOC
      - id: 103
        adapter: eth4
        ip: 10.255.0.14
        mask: 30
        zone: MGT
    custom_rules:
      - ruleset: LAN-SOC
        rule_num: 100
        accept: True
        src_ip: 100.10.10.2
        dst_ip: 100.10.30.5
        dst_port: 1514
        dst_proto: udp

- name: Add route to SOC
  vyos_static_route:
    prefix: 10.10.10.0/24
    next_hop: 100.10.10.1
