---
- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5
    
- name: Gather facts
  setup:

- name: Select VyOS config
  include_tasks: '{{vyos_type}}.yml'
