---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Gather facts
  setup:

- name: Change the hostname
  win_hostname:
    name: '{{ hostname }}'
  register: res

- name: Reboot
  win_reboot:
    msg: "Server config in progress; rebooting..."
  when: res.reboot_required
