---
# tasks file for modoboa-config


#### TODO###
#  - Restrict management access to MGT net only

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

# - name: Clean system (Uninstall if already installed)
#   include_tasks: clean.yml

- name: Disable default config
  shell: a2dissite 000-default.conf
  ignore_errors: yes

- name: Disable vhosts config
  shell: a2dissite vhosts.conf
  ignore_errors: yes

- name: delete file
  file:
    path: /etc/apache2/sites-available/vhosts.conf
    state: absent

- name: Enable necessary Apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
    - proxy_ajp
    - rewrite
    - deflate
    - headers
    - proxy_connect
    - proxy_html
    - ssl

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: create vhosts file
  file:
    path: /etc/apache2/sites-available/vhosts.conf
    state: touch

- name: Print sites http
  debug:
    var: sites_http

- name: print server names
  debug:
    msg: Servername = {{ item.servername }}
  with_items: "{{ sites_http }}"

- name: add context
  blockinfile:
    path: /etc/apache2/sites-available/vhosts.conf
    marker: "# ANSIBLE ENTRY FOR {{ item.servername }} - HTTP"
    block: |
      <VirtualHost *:80>
        ServerName {{ item.servername }}

        #ProxyPreserveHost On

        ProxyPass / http://{{ item.target }}/
        ProxyPassReverse / http://{{ item.target }}/

      </VirtualHost>
  with_items: "{{ sites_http }}"

- name: print sites_ssl
  debug:
    msg: "{{ item.private_Key_dst }}"
  with_items: "{{ sites_ssl }}"

- name: add context https
  blockinfile:
    path: /etc/apache2/sites-available/vhosts.conf
    marker: "# ANSIBLE ENTRY FOR {{ item.servername }} - HTTPS"
    block: |
      <VirtualHost *:443>
        ServerName {{ item.servername }}

      #  ProxyPreserveHost On

        SSLEngine On
        SSLCertificateFile {{ item.certificate_file_dst }}
        SSLCertificateKeyFile {{ item.private_Key_dst }}

        ProxyPass / http://{{ item.target }}/
        ProxyPassReverse / http://{{ item.target }}/

      </VirtualHost>
  with_items: "{{ sites_ssl }}"

- name: Enable vhosts config
  shell: a2ensite vhosts.conf
  ignore_errors: yes

- name: Restart Apache
  service:
    name: apache2
    state: restarted
# - name: http-to-http
#   copy:
#     src: "{{ snap_file_path }}{{ snap_file }}"
#     dest: "{{ dest_tmp_dir }}"
#     owner: "env-admin"
#     group: "env-admin"
#
# - name: Copy snap assert file with owner and permissions
#   copy:
#     src: "{{ snap_file_path }}{{ snap_assert_file }}"
#     dest: "{{ dest_tmp_dir }}"
#     owner: "env-admin"
#     group: "env-admin"
#
# - name: Ack snap assertion
#   shell: snap ack {{ dest_tmp_dir }}{{ snap_assert_file }}"
#
# - name: Install snap assertion
#   shell: snap install {{ dest_tmp_dir }}{{ snap_file }}"
