---
# defaults file for dns

# Should the DNS server be a caching DNS server?
dns_caching_dns: yes

# A list of zones and properties per zone.
dns_zones:
  - name: localhost
    soa: localhost
    serial: 1
    refresh: 604800
    rety: 86400
    expire: 2419200
    ttl: 604800
    records:
      - name: "@"
        type: NS
        value: localhost.
      - name: "@"
        value: 127.0.0.1
      - name: "@"
        type: AAAA
        value: ::1

  - name: 127.in-addr.arpa
    ttl: 604800
    records:
      - name: "@"
        type: NS
        value: localhost.
      - name: 1.0.0
        type: PTR
        value: localhost.

  - name: 0.in-addr.arpa
    records:
      - name: "@"
        type: NS
        value: localhost.

  - name: 255.in-addr.arpa
    records:
      - name: "@"
        type: NS
        value: localhost.

  - name: citef.int #
    ttl: 604800
    ns:
      - name: ns1.citef.int.
    mx:
      - name: mail.citef.int.
    records:
      - name: ns1
        value: "10.200.0.10"
      - name: mail
        value: "10.200.0.30"



  - name: esa.int.com #
    ttl: 604800
    ns:
      - name: ns1
    records:
      - name: ns1
        value: "10.200.0.10"
      - name: www
        value: "10.200.0.20"

  - name: stargate.gal #
    ttl: 604800
    ns:
      - name: ns1
    records:
      - name: ns1
        value: "10.200.0.10"
      - name: www
        value: "10.200.0.20"

  - name: starwars.gal #
    ttl: 604800
    ns:
      - name: ns1
    records:
      - name: ns1
        value: "10.200.0.10"
      - name: www
        value: "10.200.0.20"

  - name: google.nom #
    ttl: 604800
    ns:
      - name: ns1
    records:
      - name: ns1
        value: "10.200.0.10"
      - name: "@"
        value: "10.192.0.2"



# An optional list of acls to allow recursion. ("any" and "none" are always available.)
dns_allow_recursion:
  - none

# An optional list of IPv4 on which the DNS server will listen. ("any" and "none" are always available.)
dns_options_listen_on:
  - 'any'

# A optional list of IPv6 on which the DNS server will listen. ("any" and "none" are always available.)
dns_options_listen_on_v6:
  - 'none'

# An optional list of IP which are allowed to query the server. ("any" and "none" are always available.)
# Default: "any"
# dns_options_allow_query:
#  - 'any'
#  - '127.0.0.1'

# An optional list of IP which are allowed to run a AXFR query. ("any" and "none" are always available.)
# Default: "none"
# dns_options_allow_transfer:
#   - 'none'
#   - '172.16.0.1'

# An optional setting to congifure the path where the pid file will be created.
# dns_pid_file: '/var/run/named/named.pid'

# An optional setting to forward traffic to other DNS servers.
# dns_options_forwarders:
#   - 1.1.1.1
#   - 8.8.8.8
