---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Copy Splunk Forwarder Installer to Ubuntu Endpoint
  copy:
    src: 'splunkforwarder-8.1.1-08187535c166-linux-2.6-amd64.deb'
    dest: '/tmp/splunkforwarder-8.1.1-08187535c166-linux-2.6-amd64.deb'

- name: Run Splunk Forwarder Installer on Ubuntu Endpoint
  apt:
    deb: /tmp/splunkforwarder-8.1.1-08187535c166-linux-2.6-amd64.deb


- name: Need to copy over Pexpect Python Module for Ansible Expect to be supported
  copy:
    src: 'pexpect'
    dest: '/tmp/'

- name: Install Pexpect Module on Splunk Server
  pip:
    name: /tmp/pexpect/pexpect-4.8.0-py2.py3-none-any.whl
    extra_args: '--no-index --find-links /tmp/pexpect/'

- name: Start Splunk Forwarder on Ubuntu Endpoint
  expect:
    command: /opt/splunkforwarder/bin/splunk start --accept-license
    responses:
      Please enter an administrator username: env-admin
      Please enter a new password: admin-env
      Please confirm new password: admin-env

- name: Configure the Universal Forwarder to Send to Splunk
  expect:
    command: /opt/splunkforwarder/bin/splunk add forward-server {{ hostvars.SPLUNK.vm.nics | getUserLayerIP }}:9997
    responses:
      Splunk username: env-admin
      Password: admin-env
  register: result
  failed_when:
    - result.rc != 0
    - '"forwarded-server already present" not in result.stdout'

- name: Configure the Universal Forwarder to Send /var/log to Splunk
  command: /opt/splunkforwarder/bin/splunk add monitor /var/log
  register: result
  failed_when:
    - result.rc != 0
    - '"one already exists" not in result.stderr'

- name: Copy Inputs.conf to Ubuntu
  copy:
    src: 'inputs/Linux/inputs.conf'
    dest: '/opt/splunkforwarder/etc/system/local/inputs.conf'

- name: Restart The Splunk Forwarder on Ubuntu
  command: /opt/splunkforwarder/bin/splunk restart
