---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Gather facts
  setup:

- name: Disable Windows Firewall
  community.windows.win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public
