---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Gather facts
  setup:

- win_domain_membership:
    dns_domain_name: myorg.com
    domain_admin_user: env-admin@myorg.com
    domain_admin_password: "{{ hostvars['WIN_SRV']['domain_pass'] }}"
    domain_ou_path: "OU=workstations,DC=myorg,DC=com"
    state: domain
  register: domain_state

- win_reboot:
    post_reboot_delay: 180
  when: domain_state.reboot_required
