---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Gather facts
  setup:

- name: Create bash script to connect to besthostingever.com on startup
  win_copy:
    src: onstart.bat
    dest: 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp'
