---

#produce the "interfaces" file by manually running SO setup and
#then use it via this playbook for automatic setup
- name: Configure interfaces
  template:
      src: files/interfaces
      dest: /etc/network/interfaces
      owner: root
      group: root

- name: Drop networking config
  command: ip addr flush dev {{ item }}
  with_items:
    - ens3

- name: restart network
  service:
    name: networking
    state: restarted

- name: Wait host to come up
  wait_for_connection:
    timeout: 60 # 1 min
    sleep: 5

# produce the sosrv.conf file by running the following command in SO
# and answering the questions:
#     sosetup -w sosrv.conf
- name: Copy SO setup file
  template:
    src: files/sosetup-master.conf
    dest: /root/sosrv.conf
    owner: root
    group: root

- name: Run SO setup
  shell: sosetup -f /root/sosrv.conf -y

- name: Create root group for forwarders and storage
  group:
    name: node_privileges
    state: present

- name: Add forwarders to the sudoers with no passwords
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%node_privileges'
    line: '%node_privileges ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create user for Forward SO asets
  user:
    name: forward-user
    groups: node_privileges
    append: yes
    state: present
    create_home: yes

- name: Set up authorized key for the forwarder user
  authorized_key:
    user: forward-user
    key: "{{ lookup('file', 'files/id_rsa_forward.pub') }}"
    state: present

- name: create user for Storage SO asets
  user:
    name: storage-user
    groups: node_privileges
    append: yes
    state: present
    create_home: yes

- name: Set up authorized key for the forwarder user
  authorized_key:
    user: storage-user
    key: "{{ lookup('file', 'files/id_rsa_storage.pub') }}"
    state: present

- name: Whitelist sensors and analyst
  lineinfile:
    path: /var/ossec/etc/ossec.conf
    regexp: '^    <white_list>{{ item }}</white_list>'
    insertbefore: '^  </global>'
    line: '    <white_list>{{ item }}</white_list>'
    firstmatch: yes
  with_items:
    - 100.10.30.5
    - 100.10.30.6
    - 100.10.30.7
    - 100.10.30.4
    - 100.10.30.3
