---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5
- name: Gather facts
  setup:

- name: config SO
  include_tasks: tasks/config-so.yml
  tags: so-config
