---

- name: Wait host to come up
  wait_for_connection:
    timeout:  36000 # 10 hours
    sleep: 5

- name: Gather facts
  setup:

- name: Change the hostname
  win_hostname:
    name: 'MyOrgDC'
  register: res

- name: Reboot
  win_reboot:
    msg: "Server config in progress; rebooting..."
    post_reboot_delay: 40
  when: res.reboot_required

- name: Install AD Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result
  ignore_unreachable: true

- name: Create new forest
  win_domain:
    dns_domain_name: myorg.com
    safe_mode_password: SafeModePass
  register: result
  ignore_unreachable: true

- name: Reboot after creation
  win_reboot:
    msg: "Server config in progress; rebooting..."
    post_reboot_delay: 180
    reboot_timeout: 20
  ignore_errors: true
